name: client_leger
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.2.5 <4.0.0'

dependencies:
    google_sign_in: ^6.2.1
    font_awesome_flutter: ^10.7.0
    flutter:
        sdk: flutter
    email_validator: ^2.1.17
    firebase_core: ^2.25.3
    firebase_auth: ^4.17.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/logo/logo.png
        - assets/logo/google_logo.png
    fonts:
        - family: Pirata
          fonts:
              - asset: fonts/Pirata.ttf
