version: '3'

services:
    spot-seven:
        build:
            context: .
            target: development
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - uploads:/app/uploads
            - differences:/app/assets/differences
            - ./server:/app/server
            - ./common:/app/common
        depends_on:
            - db
        env_file:
            - ./server/.env
        entrypoint: ['bash', '-c', './init.sh']

    db:
        image: postgres
        env_file:
            - ./server/.env
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
        ports:
            - 5432:5432
volumes:
    uploads:
    differences:
