version: '3'

services:
    spot-seven:
        build:
            context: .
            target: development
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - uploads:/app/uploads
            - differences:/app/assets/differences
            - ./server:/app/server
        depends_on:
            - db
        env_file:
            - ./server/.env
        command: npm run start:debug

    db:
        image: postgres
        env_file:
            - ./server/.env
        ports:
            - 5432:5432
volumes:
    uploads:
    differences:
