version: '3'

services:
    traefik:
        image: traefik
        command: --api.insecure=true
            --providers.docker
            --providers.docker.exposedByDefault=false
            --entrypoints.websecure.address=:443
            --entrypoints.web.address=:80
            --entrypoints.web.http.redirections.entryPoint.to=websecure
            --entrypoints.web.http.redirections.entryPoint.scheme=https
            --entrypoints.web.http.redirections.entrypoint.permanent=true
            --certificatesresolvers.myresolver.acme.email=romain.lebbadi-breteau@polymtl.ca
            --certificatesresolvers.myresolver.acme.storage=acme.json
            --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./acme.json:/acme.json

    web:
        image: ${IMAGE_TAG}
        volumes:
            - uploads:/app/uploads
            - differences:/app/assets/differences
        environment:
            - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
        labels:
            - traefik.enable=true
            - traefik.http.routers.mysite.rule=Host(`${DOMAIN_NAME}`)
            - traefik.http.routers.mysite.tls=true
            - traefik.http.routers.mysite.tls.certresolver=myresolver

volumes:
    uploads:
    differences:
